# Generated by Django 5.2.9 on 2025-12-29 14:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariciliksayfasi',
            name='baslik',
            field=models.CharField(default='Arıcılık', help_text='Arıcılık sayfasının başlığı', max_length=200, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AlterField(
            model_name='ariciliksayfasi',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi (otomatik güncellenir)', verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='ariciliksayfasi',
            name='icerik',
            field=ckeditor.fields.RichTextField(help_text='Arıcılık sayfasının içeriğini buraya yazın. Yazı tipi, renk, resim ekleme gibi özellikleri kullanabilirsiniz.', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='ariciliksayfasi',
            name='resim',
            field=models.ImageField(blank=True, help_text='Arıcılık sayfası için bir resim yükleyin (isteğe bağlı)', null=True, upload_to='aricilik/', verbose_name='Sayfa Resmi'),
        ),
        migrations.AlterField(
            model_name='baglanti',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Bu bağlantı hakkında kısa bir açıklama (isteğe bağlı)', null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='baglanti',
            name='aktif',
            field=models.BooleanField(default=True, help_text='Bu kutuyu işaretlerseniz bağlantı web sitesinde görünür olur.', verbose_name='Yayında Göster'),
        ),
        migrations.AlterField(
            model_name='baglanti',
            name='baslik',
            field=models.CharField(help_text="Bağlantının adını yazın. Örnek: 'Türkiye Arıcılar Birliği'", max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='baglanti',
            name='logo',
            field=models.ImageField(blank=True, help_text='Bağlantı için bir logo resmi yükleyin (isteğe bağlı)', null=True, upload_to='baglantilar/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='baglanti',
            name='sira',
            field=models.IntegerField(default=0, help_text='Bağlantıların sıralaması için kullanılır. Düşük sayı önce görünür.', verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='baglanti',
            name='url',
            field=models.URLField(help_text='Tam web sitesi adresini yazın. Örnek: https://www.example.com', verbose_name='Web Sitesi Adresi'),
        ),
        migrations.AlterField(
            model_name='baglanti',
            name='yeni_sekmede_ac',
            field=models.BooleanField(default=True, help_text='İşaretli olursa bağlantı yeni bir sekmede açılır.', verbose_name='Yeni Sekmede Aç'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='aktif',
            field=models.BooleanField(default=True, help_text='Bu kutuyu işaretlerseniz duyuru web sitesinde görünür olur.', verbose_name='Yayında Göster'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='baslik',
            field=models.CharField(help_text="Duyuru başlığını buraya yazın. Örnek: 'Genel Kurul Toplantısı'", max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi (otomatik güncellenir)', verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='icerik',
            field=ckeditor.fields.RichTextField(help_text='Duyurunun detaylı içeriğini buraya yazın. Yazı tipi, renk, resim ekleme gibi özellikleri kullanabilirsiniz.', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='ozet',
            field=models.TextField(help_text='Duyurunun kısa özeti (maksimum 500 karakter). Ana sayfada görünecek.', max_length=500, verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='resim',
            field=models.ImageField(blank=True, help_text='Duyuru için bir kapak resmi seçin (isteğe bağlı). Önerilen boyut: 800x600 piksel.', null=True, upload_to='duyurular/', verbose_name='Kapak Resmi'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='sira',
            field=models.IntegerField(default=0, help_text='Duyuruların sıralaması için kullanılır. Düşük sayı önce görünür.', verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='slug',
            field=models.SlugField(blank=True, help_text='Bu alan otomatik oluşturulur. Genelde değiştirmenize gerek yok.', max_length=200, unique=True, verbose_name='URL Adresi'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='yayin_tarihi',
            field=models.DateTimeField(auto_now_add=True, help_text='Duyurunun yayınlanma tarihi (otomatik oluşturulur)', verbose_name='Yayın Tarihi'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='aktif',
            field=models.BooleanField(default=True, help_text='Bu kutuyu işaretlerseniz haber web sitesinde görünür olur.', verbose_name='Yayında Göster'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='baslik',
            field=models.CharField(help_text="Haber başlığını buraya yazın. Örnek: 'Yeni Proje Başladı'", max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi (otomatik güncellenir)', verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='icerik',
            field=ckeditor.fields.RichTextField(help_text='Haberin detaylı içeriğini buraya yazın. Yazı tipi, renk, resim ekleme gibi özellikleri kullanabilirsiniz.', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='ozet',
            field=models.TextField(help_text='Haberin kısa özeti (maksimum 500 karakter). Ana sayfada görünecek.', max_length=500, verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='resim',
            field=models.ImageField(blank=True, help_text='Haber için bir kapak resmi seçin (isteğe bağlı). Önerilen boyut: 800x600 piksel.', null=True, upload_to='haberler/', verbose_name='Kapak Resmi'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='sira',
            field=models.IntegerField(default=0, help_text='Haberlerin sıralaması için kullanılır. Düşük sayı önce görünür.', verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='slug',
            field=models.SlugField(blank=True, help_text='Bu alan otomatik oluşturulur. Genelde değiştirmenize gerek yok.', max_length=200, unique=True, verbose_name='URL Adresi'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='yayin_tarihi',
            field=models.DateTimeField(auto_now_add=True, help_text='Haberin yayınlanma tarihi (otomatik oluşturulur)', verbose_name='Yayın Tarihi'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='baslik',
            field=models.CharField(default='Hakkımızda', help_text='Hakkımızda sayfasının başlığı', max_length=200, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi (otomatik güncellenir)', verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='icerik',
            field=ckeditor.fields.RichTextField(help_text='Hakkımızda sayfasının içeriğini buraya yazın. Yazı tipi, renk, resim ekleme gibi özellikleri kullanabilirsiniz.', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='resim',
            field=models.ImageField(blank=True, help_text='Hakkımızda sayfası için bir resim yükleyin (isteğe bağlı)', null=True, upload_to='hakkimizda/', verbose_name='Sayfa Resmi'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='aktif',
            field=models.BooleanField(default=True, help_text='Bu kutuyu işaretlerseniz proje web sitesinde görünür olur.', verbose_name='Yayında Göster'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='baslangic_tarihi',
            field=models.DateField(blank=True, help_text='Projenin başladığı tarih (isteğe bağlı)', null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='baslik',
            field=models.CharField(help_text="Proje başlığını buraya yazın. Örnek: 'Arı Dostu Köy Projesi'", max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='bitis_tarihi',
            field=models.DateField(blank=True, help_text='Projenin bittiği tarih (isteğe bağlı)', null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='icerik',
            field=ckeditor.fields.RichTextField(help_text='Projenin detaylı açıklamasını buraya yazın. Yazı tipi, renk, resim ekleme gibi özellikleri kullanabilirsiniz.', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='ozet',
            field=models.TextField(help_text='Projenin kısa özeti (maksimum 500 karakter). Projeler sayfasında görünecek.', max_length=500, verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='resim',
            field=models.ImageField(blank=True, help_text='Proje için bir resim seçin (isteğe bağlı). Önerilen boyut: 800x600 piksel.', null=True, upload_to='projeler/', verbose_name='Proje Resmi'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='sira',
            field=models.IntegerField(default=0, help_text='Projelerin sıralaması için kullanılır. Düşük sayı önce görünür.', verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='slug',
            field=models.SlugField(blank=True, help_text='Bu alan otomatik oluşturulur. Genelde değiştirmenize gerek yok.', max_length=200, unique=True, verbose_name='URL Adresi'),
        ),
    ]
