# Generated by Django 5.2.9 on 2025-12-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ariciliksayfasi_baslik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_adi', models.CharField(default='Kütahya Arı Yetiştiricileri Birliği', help_text='Web sitesinin adı (üst menüde görünecek)', max_length=200, verbose_name='Site Adı')),
                ('logo', models.ImageField(blank=True, help_text='Site logosu (önerilen boyut: 200x200 piksel veya daha büyük, şeffaf arka planlı PNG)', null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text="Site favicon'u (tarayıcı sekmesinde görünecek, önerilen: 32x32 veya 16x16 piksel)", null=True, upload_to='site/', verbose_name='Favicon')),
                ('telefon', models.CharField(blank=True, help_text='İletişim telefonu (örnek: +90 274 XXX XX XX)', max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, help_text='İletişim e-posta adresi', max_length=254, null=True, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, help_text='Birlik adresi', null=True, verbose_name='Adres')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook sayfası linki (isteğe bağlı)', null=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram sayfası linki (isteğe bağlı)', null=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter sayfası linki (isteğe bağlı)', null=True, verbose_name='Twitter URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube kanalı linki (isteğe bağlı)', null=True, verbose_name='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn sayfası linki (isteğe bağlı)', null=True, verbose_name='LinkedIn URL')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi (otomatik güncellenir)', verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
